Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for pi_feat, pi_samp, size in [(pi_feat_ncoot, pi_samp_ncoot, 'alpha=0'), (pi_feat_half, pi_samp_half, 'alpha=0.5'), (pi_feat_ngw, pi_samp_ngw, 'alpha=1')]:
    
    _, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    sns.heatmap(pd.DataFrame(pi_feat, index=adt_annotated.columns, columns=rna_annotated.columns), ax=ax1, cmap='Blues', square=True)
    ax2.spy(pi_samp, precision=0.0001, markersize=3)
    plt.show()
------------------

----- stderr -----
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/matrix.py:202: RuntimeWarning: All-NaN slice encountered
  vmin = np.nanmin(calc_data)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/matrix.py:207: RuntimeWarning: All-NaN slice encountered
  vmax = np.nanmax(calc_data)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[17], line 5[0m
[1;32m      1[0m [38;5;28;01mfor[39;00m pi_feat, pi_samp, size [38;5;129;01min[39;00m [(pi_feat_ncoot, pi_samp_ncoot, [38;5;124m'[39m[38;5;124malpha=0[39m[38;5;124m'[39m), (pi_feat_half, pi_samp_half, [38;5;124m'[39m[38;5;124malpha=0.5[39m[38;5;124m'[39m), (pi_feat_ngw, pi_samp_ngw, [38;5;124m'[39m[38;5;124malpha=1[39m[38;5;124m'[39m)]:
[1;32m      3[0m     _, (ax1, ax2) [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m2[39m, figsize[38;5;241m=[39m([38;5;241m12[39m, [38;5;241m5[39m))
[0;32m----> 5[0m     [43msns[49m[38;5;241;43m.[39;49m[43mheatmap[49m[43m([49m[43mpd[49m[38;5;241;43m.[39;49m[43mDataFrame[49m[43m([49m[43mpi_feat[49m[43m,[49m[43m [49m[43mindex[49m[38;5;241;43m=[39;49m[43madt_annotated[49m[38;5;241;43m.[39;49m[43mcolumns[49m[43m,[49m[43m [49m[43mcolumns[49m[38;5;241;43m=[39;49m[43mrna_annotated[49m[38;5;241;43m.[39;49m[43mcolumns[49m[43m)[49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max1[49m[43m,[49m[43m [49m[43mcmap[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mBlues[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43msquare[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m      6[0m     ax2[38;5;241m.[39mspy(pi_samp, precision[38;5;241m=[39m[38;5;241m0.0001[39m, markersize[38;5;241m=[39m[38;5;241m3[39m)
[1;32m      7[0m     plt[38;5;241m.[39mshow()

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/matrix.py:459[0m, in [0;36mheatmap[0;34m(data, vmin, vmax, cmap, center, robust, annot, fmt, annot_kws, linewidths, linecolor, cbar, cbar_kws, cbar_ax, square, xticklabels, yticklabels, mask, ax, **kwargs)[0m
[1;32m    457[0m [38;5;28;01mif[39;00m square:
[1;32m    458[0m     ax[38;5;241m.[39mset_aspect([38;5;124m"[39m[38;5;124mequal[39m[38;5;124m"[39m)
[0;32m--> 459[0m [43mplotter[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43max[49m[43m,[49m[43m [49m[43mcbar_ax[49m[43m,[49m[43m [49m[43mkwargs[49m[43m)[49m
[1;32m    460[0m [38;5;28;01mreturn[39;00m ax

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/matrix.py:306[0m, in [0;36m_HeatMapper.plot[0;34m(self, ax, cax, kws)[0m
[1;32m    303[0m     kws[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mvmax[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39mvmax)
[1;32m    305[0m [38;5;66;03m# Draw the heatmap[39;00m
[0;32m--> 306[0m mesh [38;5;241m=[39m [43max[49m[38;5;241;43m.[39;49m[43mpcolormesh[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mplot_data[49m[43m,[49m[43m [49m[43mcmap[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcmap[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkws[49m[43m)[49m
[1;32m    308[0m [38;5;66;03m# Set the axis limits[39;00m
[1;32m    309[0m ax[38;5;241m.[39mset(xlim[38;5;241m=[39m([38;5;241m0[39m, [38;5;28mself[39m[38;5;241m.[39mdata[38;5;241m.[39mshape[[38;5;241m1[39m]), ylim[38;5;241m=[39m([38;5;241m0[39m, [38;5;28mself[39m[38;5;241m.[39mdata[38;5;241m.[39mshape[[38;5;241m0[39m]))

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/__init__.py:1446[0m, in [0;36m_preprocess_data.<locals>.inner[0;34m(ax, data, *args, **kwargs)[0m
[1;32m   1443[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[1;32m   1444[0m [38;5;28;01mdef[39;00m [38;5;21minner[39m(ax, [38;5;241m*[39margs, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m   1445[0m     [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 1446[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43max[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;28;43mmap[39;49m[43m([49m[43msanitize_sequence[49m[43m,[49m[43m [49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   1448[0m     bound [38;5;241m=[39m new_sig[38;5;241m.[39mbind(ax, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1449[0m     auto_label [38;5;241m=[39m (bound[38;5;241m.[39marguments[38;5;241m.[39mget(label_namer)
[1;32m   1450[0m                   [38;5;129;01mor[39;00m bound[38;5;241m.[39mkwargs[38;5;241m.[39mget(label_namer))

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/axes/_axes.py:6227[0m, in [0;36mAxes.pcolormesh[0;34m(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)[0m
[1;32m   6223[0m     C [38;5;241m=[39m C[38;5;241m.[39mravel()
[1;32m   6225[0m kwargs[38;5;241m.[39msetdefault([38;5;124m'[39m[38;5;124msnap[39m[38;5;124m'[39m, mpl[38;5;241m.[39mrcParams[[38;5;124m'[39m[38;5;124mpcolormesh.snap[39m[38;5;124m'[39m])
[0;32m-> 6227[0m collection [38;5;241m=[39m [43mmcoll[49m[38;5;241;43m.[39;49m[43mQuadMesh[49m[43m([49m
[1;32m   6228[0m [43m    [49m[43mcoords[49m[43m,[49m[43m [49m[43mantialiased[49m[38;5;241;43m=[39;49m[43mantialiased[49m[43m,[49m[43m [49m[43mshading[49m[38;5;241;43m=[39;49m[43mshading[49m[43m,[49m
[1;32m   6229[0m [43m    [49m[43marray[49m[38;5;241;43m=[39;49m[43mC[49m[43m,[49m[43m [49m[43mcmap[49m[38;5;241;43m=[39;49m[43mcmap[49m[43m,[49m[43m [49m[43mnorm[49m[38;5;241;43m=[39;49m[43mnorm[49m[43m,[49m[43m [49m[43malpha[49m[38;5;241;43m=[39;49m[43malpha[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   6230[0m collection[38;5;241m.[39m_scale_norm(norm, vmin, vmax)
[1;32m   6232[0m coords [38;5;241m=[39m coords[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m2[39m)  [38;5;66;03m# flatten the grid structure; keep x, y[39;00m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/collections.py:1939[0m, in [0;36mQuadMesh.__init__[0;34m(self, coordinates, antialiased, shading, **kwargs)[0m
[1;32m   1936[0m [38;5;28mself[39m[38;5;241m.[39m_bbox[38;5;241m.[39mupdate_from_data_xy([38;5;28mself[39m[38;5;241m.[39m_coordinates[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m2[39m))
[1;32m   1937[0m [38;5;66;03m# super init delayed after own init because array kwarg requires[39;00m
[1;32m   1938[0m [38;5;66;03m# self._coordinates and self._shading[39;00m
[0;32m-> 1939[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   1940[0m [38;5;28mself[39m[38;5;241m.[39mset_mouseover([38;5;28;01mFalse[39;00m)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/_api/deprecation.py:454[0m, in [0;36mmake_keyword_only.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    448[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m name_idx:
[1;32m    449[0m     warn_deprecated(
[1;32m    450[0m         since, message[38;5;241m=[39m[38;5;124m"[39m[38;5;124mPassing the [39m[38;5;132;01m%(name)s[39;00m[38;5;124m [39m[38;5;132;01m%(obj_type)s[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    451[0m         [38;5;124m"[39m[38;5;124mpositionally is deprecated since Matplotlib [39m[38;5;132;01m%(since)s[39;00m[38;5;124m; the [39m[38;5;124m"[39m
[1;32m    452[0m         [38;5;124m"[39m[38;5;124mparameter will become keyword-only [39m[38;5;132;01m%(removal)s[39;00m[38;5;124m.[39m[38;5;124m"[39m,
[1;32m    453[0m         name[38;5;241m=[39mname, obj_type[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m()[39m[38;5;124m"[39m)
[0;32m--> 454[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/collections.py:201[0m, in [0;36mCollection.__init__[0;34m(self, edgecolors, facecolors, linewidths, linestyles, capstyle, joinstyle, antialiaseds, offsets, offset_transform, norm, cmap, pickradius, hatch, urls, zorder, **kwargs)[0m
[1;32m    198[0m [38;5;28mself[39m[38;5;241m.[39m_offset_transform [38;5;241m=[39m offset_transform
[1;32m    200[0m [38;5;28mself[39m[38;5;241m.[39m_path_effects [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m--> 201[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_internal_update[49m[43m([49m[43mkwargs[49m[43m)[49m
[1;32m    202[0m [38;5;28mself[39m[38;5;241m.[39m_paths [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/artist.py:1223[0m, in [0;36mArtist._internal_update[0;34m(self, kwargs)[0m
[1;32m   1216[0m [38;5;28;01mdef[39;00m [38;5;21m_internal_update[39m([38;5;28mself[39m, kwargs):
[1;32m   1217[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   1218[0m [38;5;124;03m    Update artist properties without prenormalizing them, but generating[39;00m
[1;32m   1219[0m [38;5;124;03m    errors as if calling `set`.[39;00m
[1;32m   1220[0m 
[1;32m   1221[0m [38;5;124;03m    The lack of prenormalization is to maintain backcompatibility.[39;00m
[1;32m   1222[0m [38;5;124;03m    """[39;00m
[0;32m-> 1223[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_update_props[49m[43m([49m
[1;32m   1224[0m [43m        [49m[43mkwargs[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{cls.__name__}[39;49;00m[38;5;124;43m.set() got an unexpected keyword argument [39;49m[38;5;124;43m"[39;49m
[1;32m   1225[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{prop_name!r}[39;49;00m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/artist.py:1199[0m, in [0;36mArtist._update_props[0;34m(self, props, errfmt)[0m
[1;32m   1196[0m             [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mcallable[39m(func):
[1;32m   1197[0m                 [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m   1198[0m                     errfmt[38;5;241m.[39mformat([38;5;28mcls[39m[38;5;241m=[39m[38;5;28mtype[39m([38;5;28mself[39m), prop_name[38;5;241m=[39mk))
[0;32m-> 1199[0m             ret[38;5;241m.[39mappend([43mfunc[49m[43m([49m[43mv[49m[43m)[49m)
[1;32m   1200[0m [38;5;28;01mif[39;00m ret:
[1;32m   1201[0m     [38;5;28mself[39m[38;5;241m.[39mpchanged()

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/collections.py:1986[0m, in [0;36mQuadMesh.set_array[0;34m(self, A)[0m
[1;32m   1981[0m     [38;5;28;01mif[39;00m shape [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m ok_shapes:
[1;32m   1982[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1983[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mFor X ([39m[38;5;132;01m{[39;00mwidth[38;5;132;01m}[39;00m[38;5;124m) and Y ([39m[38;5;132;01m{[39;00mheight[38;5;132;01m}[39;00m[38;5;124m) with [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m_shading[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m   1984[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mshading, A should have shape [39m[38;5;124m"[39m
[1;32m   1985[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;28mmap[39m([38;5;28mstr[39m,[38;5;250m [39mok_shapes))[38;5;132;01m}[39;00m[38;5;124m, not [39m[38;5;132;01m{[39;00mA[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m-> 1986[0m [38;5;28;01mreturn[39;00m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mset_array[49m[43m([49m[43mA[49m[43m)[49m

File [0;32m/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/cm.py:515[0m, in [0;36mScalarMappable.set_array[0;34m(self, A)[0m
[1;32m    513[0m A [38;5;241m=[39m cbook[38;5;241m.[39msafe_masked_invalid(A, copy[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    514[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m np[38;5;241m.[39mcan_cast(A[38;5;241m.[39mdtype, [38;5;28mfloat[39m, [38;5;124m"[39m[38;5;124msame_kind[39m[38;5;124m"[39m):
[0;32m--> 515[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mImage data of dtype [39m[38;5;132;01m{[39;00mA[38;5;241m.[39mdtype[38;5;132;01m}[39;00m[38;5;124m cannot be [39m[38;5;124m"[39m
[1;32m    516[0m                     [38;5;124m"[39m[38;5;124mconverted to float[39m[38;5;124m"[39m)
[1;32m    518[0m [38;5;28mself[39m[38;5;241m.[39m_A [38;5;241m=[39m A

[0;31mTypeError[0m: Image data of dtype object cannot be converted to float

